### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Jack-ee** [Clarmy/cnmaps#1]
(xxx) C:\Users\Jkdell>pip install cnmaps
Collecting cnmaps
  Using cached cnmaps-0.1.10.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Jkdell\AppData\Local\Temp\pip-install-9qi40z8x\cnmaps_4a8842083b524713a538b30839062a41\setup.py", line 7, in <module>
          long_description = fh.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 17: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Clarmy** [comment]
@Jack-ee Hello, Jack. I realeased a new version of 0.1.11 for pypi yesterday, can you try to install again with `pip install -U cnmaps` ?

**Comment by Jack-ee** [comment]
安装成功 了，谢谢！

**Comment by Clarmy** [comment]
@Jack-ee 好的，收到。
