### ISSUE TITLE
希望 draw_map 函数中不要重复新建 CRS 对象

### ISSUE THREAD

**Issue by ZhaJiMan** [Clarmy/cnmaps#30]
画地图多边形的 `draw_map` 函数中有这样一行坐标转换的代码
`x, y = ax.projection.transform_point(*coord, src_crs=ccrs.PlateCarree())`
其中 `ccrs.PlateCarree()` 创建 `CRS` 对象的操作很费时，当多边形含有的坐标很多时，就会反复创建 `CRS` 对象，非常拖慢画图速度。
看起来包中的地图数据都基于 PlateCarree 坐标系，希望能在这个函数的开头定义 `src_crs = ccrs.PlateCarree()`，然后再在坐标转换的代码中重复使用创建好的对象，个人测试后发现这样能加快画图速度。

**Comment by Clarmy** [comment]
收到，我测试一下再给你回复。

**Comment by Clarmy** [comment]
或者你也可以直接提一个 PR 给我，我测试之后把它合并

**Comment by Clarmy** [comment]
> 我没提过 PR，需要研究一下怎么搞

这里有一些参考资料：https://chinese.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github/

**Comment by Clarmy** [comment]
PR：#31
