### ISSUE TITLE
关于程序编码问题

### ISSUE THREAD

**Issue by fuliang524** [Clarmy/cnmaps#7]
尊敬的开发者，在windows10上（pycharm）使用cnmaps库的时候出现一下的问题：
程序：
#!/usr/bin/python
# -*- coding: utf-8 -*-
# @Time    : 2022/3/1 15:18
# @Email  :
# @Author  :

import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np
from cnmaps import get_map, draw_map, clip_contours_by_map
from cnmaps.sample import load_dem

lons, lats, dem = load_dem()
jingjinji = get_map('北京')

fig = plt.figure(figsize=(10, 10),dpi=800)
ax = fig.add_subplot(111, projection=ccrs.PlateCarree())
draw_map(jingjinji, color='k')
cs = ax.contourf(lons,
                 lats,
                 dem,
                 cmap=plt.cm.terrain,
                 levels=np.linspace(-2112, dem.max(), 10))
clip_contours_by_map(cs, jingjinji)
ax.set_extent(jingjinji.get_extent(buffer=1))

plt.savefig('./jingjinji-cliped-dem.eps', bbox_inches='tight')

#******************************************
错误提示
Traceback (most recent call last):
  File "H:/pyproject/haoqixin/cliped-dem.py", line 14, in <module>
    jingjinji = get_map('北京')
  File "C:\Users\YH\anaconda3\envs\cnmaps\lib\site-packages\cnmaps\__init__.py", line 109, in get_map
    map_json = json.load(f)
  File "C:\Users\YH\anaconda3\envs\cnmaps\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 389467: illegal multibyte sequence

Process finished with exit code 1

在尝试修改pycham里面的编码为uft-8之后问题依然存在

**Comment by Clarmy** [comment]
@fuliang524 您好，这个问题已经确认是程序的bug，目前已经修复并在Windows系统的gbk编码下完成了测试，pypi上发布了新的版本，请更新版本到0.2.1： `pip install cnmaps>=0.2.1`

修复的commit：#8

**Comment by fuliang524** [comment]
非常感谢您的解答！祝好！



---- 回复的原邮件 ----
| 发件人 | Wentao ***@***.***> |
| 日期 | 2022年03月02日 01:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Clarmy/cnmaps] 关于程序编码问题 (Issue #7) |

@fuliang524 您好，这个问题已经确认是程序的bug，目前已经修复并在Windows系统的gbk编码下完成了测试，pypi上发布了新的版本，请更新版本到0.2.1： pip install cnmaps>=0.2.1

修复的commit：#8

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
